spring:
  application:
    name: Red Social Foro Hub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forohubdb
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
        open-in-view: false
    server:
      error:
        include-stacktrace: never
